name: plibrary
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^7.0.0
  cloud_firestore: ^1.0.6
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.3
  flow_builder: ^0.0.2
  flutter_bloc: ^7.0.0
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.6
  animated_text_kit: ^4.2.1
  formz: ^0.3.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
